### PR TITLE
 #19 Homepage design / skeleton framework

### LINKED ISSUE #19: Set up initial home page/landing page
Design and setup the initial landing/homepage of the site - mockup available in google drive

### PR DESCRIPTION
**Pull request by g1isgone**
* Homepage design
* Homepage/club info 
* Typewriter animation lays over main homepage image 
* Contact us icons at the bottom

### CODE REVIEW

**Review by naylynn-TR — APPROVED** [review]

**Review by naylynn-TR — APPROVED** [review]
what would the ‘Contact Us’ section look like with the previous color (aqua/teal)?

**Comment by g1isgone** [comment]
> what would the ‘Contact Us’ section look like with the previous color (aqua/teal)?
Like below: I personally liked purple more than teal bc it went from orange -> darker purple ? But up for discussion!

Screen Shot 2021-01-19 at 2 34 23 PM

**Comment by naylynn-TR** [comment]
> > what would the ‘Contact Us’ section look like with the previous color (aqua/teal)?
> > Like below: I personally liked purple more than teal bc it went from orange -> darker purple ? But up for discussion!
> 
> Screen Shot 2021-01-19 at 2 34 23 PM

The aqua matches the theme/colors in the initial image as does the orange. The least amount of colors, I think, the better. We can just vote on it though! I'm just rambling.

**Comment by g1isgone** [comment]
> > > what would the ‘Contact Us’ section look like with the previous color (aqua/teal)?
> > > Like below: I personally liked purple more than teal bc it went from orange -> darker purple ? But up for discussion!
> > 
> > 
> > Screen Shot 2021-01-19 at 2 34 23 PM
> 
> The aqua matches the theme/colors in the initial image as does the orange. The least amount of colors, I think, the better. We can just vote on it though! I'm just rambling.

Okay - let's vote in our next meeting :)

**Pull request merged**
